Demo_Upload_Multiple_Images/Models/Sub_Images.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Upload_Multiple_Images.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Sub_Images
    {
        public int id { get; set; }
        public string url_images { get; set; }
        public Nullable<int> product_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}

Demo_Upload_Multiple_Images/Controllers/Sub_ImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Demo_Upload_Multiple_Images.Models;

namespace Demo_Upload_Multiple_Images.Controllers
{
    public class Sub_ImagesController : Controller
    {
        private Demo_Multiple_ImagesEntities db = new Demo_Multiple_ImagesEntities();

        // GET: Sub_Images
        public ActionResult Index()
        {
            var sub_Images = db.Sub_Images.Include(s => s.Product);
            return View(sub_Images.ToList());
        }

        // GET: Sub_Images/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sub_Images sub_Images = db.Sub_Images.Find(id);
            if (sub_Images == null)
            {
                return HttpNotFound();
            }
            return View(sub_Images);
        }

        // GET: Sub_Images/Create
        public ActionResult Create()
        {
            ViewBag.product_id = new SelectList(db.Products, "id", "name");
            return View();
        }

        // POST: Sub_Images/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "id,url_images,product_id")] Sub_Images sub_Images)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Sub_Images.Add(sub_Images);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.product_id = new SelectList(db.Products, "id", "name", sub_Images.product_id);
        //    return View(sub_Images);
        //}

        public ActionResult Create(Sub_Images sub_Images, HttpPostedFileBase[] photo)
        {
            ViewBag.product_id = new SelectList(db.Products, "id", "name", sub_Images.product_id);
            int? id_product = sub_Images.product_id;
            if (photo != null)
            {
                List<string> file = new List<string>();
                foreach (var photos in photo)
                {
                    photos.SaveAs(Server.MapPath("~/Content/images/" + photos.FileName));
                    //file.Add(photos.FileName);
                    Sub_Images sub_Images1 = new Sub_Images();
                    sub_Images1.url_images = photos.FileName;
                    sub_Images1.product_id = id_product;
                    db.Entry(sub_Images1).State = EntityState.Added;
                    db.SaveChanges();
                }
            }
            //else
            //{
            //    string pictures = "no-image.png";
            //    sub_Images.url_images = pictures;
            //}
            //db.Sub_Images.Add(sub_Images);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: Sub_Images/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sub_Images sub_Images = db.Sub_Images.Find(id);
            if (sub_Images == null)
            {
                return HttpNotFound();
            }
            ViewBag.product_id = new SelectList(db.Products, "id", "name", sub_Images.product_id);
            return View(sub_Images);
        }

        // POST: Sub_Images/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,url_images,product_id")] Sub_Images sub_Images)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sub_Images).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.product_id = new SelectList(db.Products, "id", "name", sub_Images.product_id);
            return View(sub_Images);
        }

        // GET: Sub_Images/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sub_Images sub_Images = db.Sub_Images.Find(id);
            if (sub_Images == null)
            {
                return HttpNotFound();
            }
            return View(sub_Images);
        }

        // POST: Sub_Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sub_Images sub_Images = db.Sub_Images.Find(id);
            db.Sub_Images.Remove(sub_Images);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Demo_Upload_Multiple_Images/Views/Sub_Images/Create.cshtml
@model Demo_Upload_Multiple_Images.Models.Sub_Images

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Create","Sub_Images",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sub_Images</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.url_images, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">                
                <input type="file" name="photo" multiple="multiple" />
                @*@Html.EditorFor(model => model.url_images, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.ValidationMessageFor(model => model.url_images, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_id, "product_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("product_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.product_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Demo_Upload_Multiple_Images/Views/Sub_Images/Delete.cshtml
@model Demo_Upload_Multiple_Images.Models.Sub_Images

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sub_Images</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.url_images)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url_images)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Demo_Upload_Multiple_Images/Views/Sub_Images/Details.cshtml
@model Demo_Upload_Multiple_Images.Models.Sub_Images

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Sub_Images</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.url_images)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url_images)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Demo_Upload_Multiple_Images/Views/Sub_Images/Edit.cshtml
@model Demo_Upload_Multiple_Images.Models.Sub_Images

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sub_Images</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.url_images, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url_images, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url_images, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_id, "product_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("product_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.product_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Demo_Upload_Multiple_Images/Views/Sub_Images/Index.cshtml
@model IEnumerable<Demo_Upload_Multiple_Images.Models.Sub_Images>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Product.images)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url_images)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product.images)
            <img src="~/Content/images/@Html.DisplayFor(modelIten => item.Product.images)" width="120px" height="120px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.url_images)
            <img src="~/Content/images/@Html.DisplayFor(modelIten => item.url_images)" width="120px" height="120px" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>